export const ADD_COMMENT_TROPHY = 'ADD_COMMENT_TROPHY';
export const ADD_COMMENT_CHALLENGE = 'ADD_COMMENT_CHALLENGE';
export const ADD_COMMENT_ACCEPTANCE = 'ADD_COMMENT_ACCEPTANCE';
export const ADD_TROPHY_COMMENT_ACCEPTANCES = 'ADD_TROPHY_COMMENT_ACCEPTANCES';
export const SET_LIKE_COMMENT = 'SET_LIKE_COMMENT';
export const UNSET_LIKE_COMMENT = 'UNSET_LIKE_COMMENT';
export const DELETE_COMMENT = 'DELETE_COMMENT';
