// Naming:
// ACTION_ENTITY_RESULT

export const OPEN_MODAL = 'OPEN_MODAL';
export const OPEN_EXTEND_MODAL = 'OPEN_EXTEND_MODAL';
export const EXPAND_MODAL = 'EXPAND_MODAL';
export const SHRINK_MODAL = 'SHRINK_MODAL';
export const CLOSE_MODAL = 'CLOSE_MODAL';
export const CLOSE_EXTEND_MODAL = 'CLOSE_EXTEND_MODAL';
