export const GET_SEARCH_USERS = 'GET_SEARCH_USERS';
export const GET_SEARCH_CHALLENGES = 'GET_SEARCH_CHALLENGES';
export const SET_SEARCH = 'SET_SEARCH';
export const SET_SEARCH_FILTER = 'SET_SEARCH_FILTER';
export const CLEAR_SEARCH_DATA_STATE = 'CLEAR_SEARCH_DATA_STATE';
export const CLEAR_SEARCH_RESULTS_DATA_STATE = 'CLEAR_SEARCH_RESULTS_DATA_STATE';
