export const GET_TROPHIES = 'GET_TROPHIES';
export const GET_TROPHY = 'GET_TROPHY';
export const GET_TROPHY_ACCEPTANCES = 'GET_TROPHY_ACCEPTANCES';
export const TROPHY_SET_FILTER = 'TROPHY_SET_FILTER';
export const CLEAR_DATA_STATE = 'CLEAR_DATA_STATE';
export const TROPHY_RESTORE_FILTER = 'TROPHY_RESTORE_FILTER';
export const CLEAR_TROPHY_DATA_STATE = 'CLEAR_TROPHY_DATA_STATE';
