export const CREATE_USER = 'CREATE_USER';
export const GET_USER_BY_ID = 'GET_USER_BY_ID';
export const SET_REDIRECT = 'SET_REDIRECT';
export const LOGIN_USER = 'LOGIN_USER';
export const GET_USER = 'GET_USER';
export const UPDATE_USER = 'UPDATE_USER';
export const GET_USER_POSTS = 'GET_USER_POSTS';
export const GET_POSTS_LIKED = 'GET_POSTS_LIKED';
export const RESET_PASSWORD = 'RESET_PASSWORD';
export const RECOVERY_PASSWORD = 'RECOVERY_PASSWORD';
export const USER_LOADED = 'USER_LOADED';
export const USER_UNLOADED = 'USER_UNLOADED';
export const UPDATE_PROMOCODE = 'UPDATE_PROMOCODE';

export const IS_EXIST_USER = 'IS_EXIST_USER';
export const IS_EXIST_EMAIL = 'IS_EXIST_EMAIL';
export const CLEAR_USER_FORM = 'CLEAR_USER_FORM';
export const USER_LOGOUT = 'USER_LOGOUT';
export const CLEAR_STATE_EXIST_EMAIL = 'CLEAR_STATE_EXIST_EMAIL';
export const CLEAR_DATA_STATE = 'CLEAR_DATA_STATE';
export const CLEAR_ERROR_DATA_STATE = 'CLEAR_ERROR_DATA_STATE';
export const CLEAR_TEMP_DATA_STATE = 'CLEAR_TEMP_DATA_STATE';

export const SET_USER_FOLLOW = 'SET_USER_FOLLOW';
export const UNSET_USER_FOLLOW = 'UNSET_USER_FOLLOW';

export const GET_USER_FOLLOWERS = 'GET_USER_FOLLOWERS';
export const GET_USER_FOLLOWING = 'GET_USER_FOLLOWING';
export const SEND_FOLLOW_REQUEST = 'SEND_FOLLOW_REQUEST';

export const USER_FACEBOOK_CONNECTED = 'USER_FACEBOOK_CONNECTED';

export const SEND_VERIFY_PHONE = 'SEND_VERIFY_PHONE';
export const SEND_VERIFY_EMAIL = 'SEND_VERIFY_EMAIL';
export const RESEND_VERIFY_EMAIL = 'RESEND_VERIFY_EMAIL';
export const RESEND_VERIFY_PHONE = 'RESEND_VERIFY_PHONE';

export const USER_SEND_MESSAGE = 'USER_SEND_MESSAGE';
export const USER_INITIAL_CHAT = 'USER_INITIAL_CHAT';

export const GET_USER_NOTIFICATIONS = 'GET_USER_NOTIFICATIONS';
export const GET_USER_FOLLOWING_REQUESTED = 'GET_USER_FOLLOWING_REQUESTED';

export const CLEAR_STATE_NOTIFICATIONS = 'CLEAR_STATE_NOTIFICATIONS';

export const USER_ACCEPT_FOLLOWING_REQUEST = 'USER_ACCEPT_FOLLOWING_REQUEST';
export const USER_DECLINE_FOLLOWING_REQUEST = 'USER_DECLINE_FOLLOWING_REQUEST';
